spring:
  messages:
    basename: ExternalApi

api:
  banks:
    ALFA_BANK:
      currencyUrl:
        name: https://developerhub.alfabank.by:8273/partner/1.0.1/public/rates
        parameters:
      rateUrl:
        name: https://developerhub.alfabank.by:8273/partner/1.0.1/public/rates
        parameters:
    BELARUS_BANK:
      currencyUrl:
        name: https://belarusbank.by/api/kurs_cards?kursDate
        parameters:
      rateUrl:
        name: https://belarusbank.by/api/kurs_cards?kursDate
        parameters:
    NATIONAL_BANK:
      currencyUrl:
        name: https://api.nbrb.by/exrates/rates?periodicity=0
        parameters:
      rateUrl:
        name: https://api.nbrb.by/exrates/rates/{currencyCode}?ondate={date}&parammode=2
        parameters:
          - currencyCode
          - date